### PR TITLE
Update drawing context when changing canvas dimensions

### PR DESCRIPTION
**Pull request by JoshDobbin**

### CODE REVIEW

**Comment by patrimart** [comment]
Many thanks! I'll test and release this evening.

**Comment by jdobbin-hsahealthplan** [comment]
Thank you so much for sharing your awesome work! I hope my contribution helps.

**Comment by willyguevara** [comment]
Hello @JoshDobbin how can i make this resizing to work. i have the version with the adjustment but i cant resize the canvas programmatically with a variable.

**Comment by JoshDobbin** [comment]
@wilguevara I'm really sorry I never saw this until now. The deployed changes must be missing something. 

Here's what I ended up doing in my controller code:

```
this.certCanvas.width = 1000;
this.certCanvas.renderer.setAttribute(this.certCanvas.canvasRef.nativeElement, "width", String(1000));
```

where `this.certCanvas` is defined as a child view `@ViewChild('certCanvas') certCanvas` and the child view is referenced in the markup like this:

```
<ngvas #certCanvas [width]="500" [height]="500" (ready)="onNgvasInit($event)">
    <template ngFor let-f [ngForOf]="thingsToDraw">
        <ngvas-text [fill]="'#0000ff'" [x]="f.x*100" [y]="f.y*100" [width]="300" [height]="300" [text]="f.name"></ngvas-text>
    </template>
</ngvas>
```

**Pull request merged**
